// This file was generated by counterfeiter
package statedetectorfakes

import (
	"sync"

	"code.cloudfoundry.org/showmewhatyougot/statedetector"
)

type FakeStateDetector struct {
	PidsStub        func([]int) ([]int, error)
	pidsMutex       sync.RWMutex
	pidsArgsForCall []struct {
		arg1 []int
	}
	pidsReturns struct {
		result1 []int
		result2 error
	}
	pidsReturnsOnCall map[int]struct {
		result1 []int
		result2 error
	}
	DetectedProcessesStub        func() ([]int, []string, error)
	detectedProcessesMutex       sync.RWMutex
	detectedProcessesArgsForCall []struct{}
	detectedProcessesReturns     struct {
		result1 []int
		result2 []string
		result3 error
	}
	detectedProcessesReturnsOnCall map[int]struct {
		result1 []int
		result2 []string
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStateDetector) Pids(arg1 []int) ([]int, error) {
	var arg1Copy []int
	if arg1 != nil {
		arg1Copy = make([]int, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.pidsMutex.Lock()
	ret, specificReturn := fake.pidsReturnsOnCall[len(fake.pidsArgsForCall)]
	fake.pidsArgsForCall = append(fake.pidsArgsForCall, struct {
		arg1 []int
	}{arg1Copy})
	fake.recordInvocation("Pids", []interface{}{arg1Copy})
	fake.pidsMutex.Unlock()
	if fake.PidsStub != nil {
		return fake.PidsStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.pidsReturns.result1, fake.pidsReturns.result2
}

func (fake *FakeStateDetector) PidsCallCount() int {
	fake.pidsMutex.RLock()
	defer fake.pidsMutex.RUnlock()
	return len(fake.pidsArgsForCall)
}

func (fake *FakeStateDetector) PidsArgsForCall(i int) []int {
	fake.pidsMutex.RLock()
	defer fake.pidsMutex.RUnlock()
	return fake.pidsArgsForCall[i].arg1
}

func (fake *FakeStateDetector) PidsReturns(result1 []int, result2 error) {
	fake.PidsStub = nil
	fake.pidsReturns = struct {
		result1 []int
		result2 error
	}{result1, result2}
}

func (fake *FakeStateDetector) PidsReturnsOnCall(i int, result1 []int, result2 error) {
	fake.PidsStub = nil
	if fake.pidsReturnsOnCall == nil {
		fake.pidsReturnsOnCall = make(map[int]struct {
			result1 []int
			result2 error
		})
	}
	fake.pidsReturnsOnCall[i] = struct {
		result1 []int
		result2 error
	}{result1, result2}
}

func (fake *FakeStateDetector) DetectedProcesses() ([]int, []string, error) {
	fake.detectedProcessesMutex.Lock()
	ret, specificReturn := fake.detectedProcessesReturnsOnCall[len(fake.detectedProcessesArgsForCall)]
	fake.detectedProcessesArgsForCall = append(fake.detectedProcessesArgsForCall, struct{}{})
	fake.recordInvocation("DetectedProcesses", []interface{}{})
	fake.detectedProcessesMutex.Unlock()
	if fake.DetectedProcessesStub != nil {
		return fake.DetectedProcessesStub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.detectedProcessesReturns.result1, fake.detectedProcessesReturns.result2, fake.detectedProcessesReturns.result3
}

func (fake *FakeStateDetector) DetectedProcessesCallCount() int {
	fake.detectedProcessesMutex.RLock()
	defer fake.detectedProcessesMutex.RUnlock()
	return len(fake.detectedProcessesArgsForCall)
}

func (fake *FakeStateDetector) DetectedProcessesReturns(result1 []int, result2 []string, result3 error) {
	fake.DetectedProcessesStub = nil
	fake.detectedProcessesReturns = struct {
		result1 []int
		result2 []string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeStateDetector) DetectedProcessesReturnsOnCall(i int, result1 []int, result2 []string, result3 error) {
	fake.DetectedProcessesStub = nil
	if fake.detectedProcessesReturnsOnCall == nil {
		fake.detectedProcessesReturnsOnCall = make(map[int]struct {
			result1 []int
			result2 []string
			result3 error
		})
	}
	fake.detectedProcessesReturnsOnCall[i] = struct {
		result1 []int
		result2 []string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeStateDetector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.pidsMutex.RLock()
	defer fake.pidsMutex.RUnlock()
	fake.detectedProcessesMutex.RLock()
	defer fake.detectedProcessesMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeStateDetector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ statedetector.StateDetector = new(FakeStateDetector)
