// This file was generated by counterfeiter
package statedetectorfakes

import (
	"sync"

	"code.cloudfoundry.org/showmewhatyougot/statedetector"
)

type FakeDataCollector struct {
	RunStub        func(processesList []string) (string, error)
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		processesList []string
	}
	runReturns struct {
		result1 string
		result2 error
	}
	runReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDataCollector) Run(processesList []string) (string, error) {
	var processesListCopy []string
	if processesList != nil {
		processesListCopy = make([]string, len(processesList))
		copy(processesListCopy, processesList)
	}
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		processesList []string
	}{processesListCopy})
	fake.recordInvocation("Run", []interface{}{processesListCopy})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(processesList)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.runReturns.result1, fake.runReturns.result2
}

func (fake *FakeDataCollector) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeDataCollector) RunArgsForCall(i int) []string {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].processesList
}

func (fake *FakeDataCollector) RunReturns(result1 string, result2 error) {
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeDataCollector) RunReturnsOnCall(i int, result1 string, result2 error) {
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeDataCollector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeDataCollector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ statedetector.DataCollector = new(FakeDataCollector)
